### PR TITLE
Use VK_EXT_subgroup_size_control to choose subgroup size

### PR DESCRIPTION
**Pull request by marcinslusarz**
VkPhysicalDeviceVulkan11Properties.subgroupSize is weakly defined, so tell the driver that we want this particular size and no other.

### CODE REVIEW

**Comment by pixeljetstream** [comment]
have you considered exposing the potential subgroup sizes in the UI / commandline for hw that supports this extension? If you think that is beneficial maybe add this later

**Comment by pixeljetstream** [comment]
not sure what this DCO check failure thing meant @marcinslusarz maybe something you also need to check

**Comment by marcinslusarz** [comment]
No, I haven't considered it, but I think this is a good idea. I'm starting a week-long vacation now, but I'll try to implement this after I come back.

**Comment by marcinslusarz** [comment]
> not sure what this DCO check failure thing meant @marcinslusarz maybe something you also need to check

It seems there's a check that requires signed-off lines in commit messages. I assumed it was enabled by mistake as no other commit has such line.

**Pull request merged**
